CREATE TABLE Areas (
  Id TINYINT IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(100) NOT NULL
);

ALTER TABLE Areas
ADD PRIMARY KEY (Id);


CREATE TABLE Programees (
  Id TINYINT IDENTITY(1,1) NOT NULL,
  Programee SMALLINT NOT NULL,
  AreaId TINYINT NOT NULL,
  FOREIGN KEY(AreaId) REFERENCES Areas (Id)
);

ALTER TABLE Programees
ADD PRIMARY KEY (Id);


CREATE TABLE SpecificCourses (
  Id SMALLINT IDENTITY(1,1) NOT NULL, 
  Name NVARCHAR(100) NOT NULL,
  Semester TINYINT NOT NULL,
  Groups TEXT NOT NULL
);

ALTER TABLE SpecificCourses
ADD PRIMARY KEY (Id);


CREATE TABLE SharedCourses (
  Id SMALLINT IDENTITY(1,1) NOT NULL,
  Name NVARCHAR(100) NOT NULL,
  Semester TINYINT NOT NULL,
  Groups TEXT NOT NULL
);

ALTER TABLE SharedCourses
ADD PRIMARY KEY (Id);


CREATE TABLE AreaSharedCourses (
  SharedCourseId SMALLINT IDENTITY NOT NULL,
  AreaId TINYINT NOT NULL,
  FOREIGN KEY(SharedCourseId) REFERENCES SharedCourse(Id),
  FOREIGN KEY(AreaId) REFERENCES Programees (Id)
);
